sonar.projectKey=nadaBoussetta_devOps
sonar.organization=nadaboussetta
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml