# Profil de développement

# Base de données H2 en mémoire
spring.datasource.url=jdbc:h2:mem:bibliothequedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Logs détaillés
logging.level.com.bibliotheque.idf=DEBUG
