# Profil de production

# Base de données PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bibliothequedb
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Console H2 désactivée
spring.h2.console.enabled=false

# Logs
logging.level.com.bibliotheque.idf=INFO
